# Generated by Django 4.1.3 on 2022-11-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProflie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='用户名', max_length=11)),
                ('password', models.CharField(help_text='密码', max_length=32)),
                ('email', models.EmailField(help_text='邮箱', max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('avatar', models.ImageField(null=True, upload_to='avatar')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jiangtao_backend_user_profile',
            },
        ),
    ]
