# Generated by Django 4.1.3 on 2022-12-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_userproflie_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproflie',
            name='password',
            field=models.CharField(help_text='密码', max_length=128),
        ),
    ]
